### ISSUE TITLE
Compatible with Gravit

### ISSUE THREAD

**Issue by ghost** [micahlt/scratchimportfixer#1]
Could it be possible to find a way to have gravit svgs compatible with this converter, they don't import exactly right either.

**Comment by micahlt** [comment]
@geographix What isn't imported correctly with Gravit SVGs?

**Comment by ghost** [comment]
Well, compound shapes seem to undo when in and unlike bitmap files it doesn't resize to fit (that would be convenient).

**Comment by ghost** [comment]
@micahlt Just reminding you of this open issue...

**Comment by micahlt** [comment]
Yeah, but I'm on vacation.  It'll be awhile before I start working on
this.  If you want to help you can compare Gravit exports' code with the
SVE's code over at llk and find out what's going wrong.

**Comment by ghost** [comment]
Okay, yeah, I understand your on vacation, I kinda wanted to bump this though because it was rather forgotten about! Anyways, have a good holiday!
